### ISSUE TITLE
[Question] Remote Server support?

### ISSUE THREAD

**Issue by joex92** [olilarkin/wsserver#2]
Hi! I have used this package on Max, and I love it. It's very useful, but I'm wondering if it is possible to run the server remotely and communicate with the web server to control a patch and viceversa, control the web server with the patch. I have done this locally, just wondering if it's possible to run a web server outside of Max and achieve the same.

**Comment by olilarkin** [comment]
Not sure I really understand your Question. You can run a WebServer Outside of Max, e.g. using node and communicate with Max via OSC. You can also make this work over a network if that's what your question is about, as long as all the ports are open et cetera. These days I would use the node object in Max rather than this external￼

**Comment by joex92** [comment]
oh ok... I used this package because it was easier for me to understand it that the node object itself... anyways, do you know a library that can be used to do the communication over the network? because I want to manipulate the website content live so any person watching the website, would see changes live...

**Comment by olilarkin** [comment]
It is not at all clear to me what you want to do, or why you couldn't do what I think you want to do using html/js as in the example. I'm quite busy so I think you'd be best off asking e.g. on the max forum

**Comment by olilarkin** [comment]
(it's a long time since i did this)

**Comment by joex92** [comment]
oh ok... sorry then... but I want to control a website live WITH Max, and I wanted to know if that is possible with this package... anyways thanks, I'll keep digging how to achieve what I need...
